# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='answer',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
