# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0002_puzzle_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='location',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='point',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
