# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0003_auto_20171129_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
