# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0007_playergamehistory_solved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergamehistory',
            name='id',
        ),
        migrations.AlterField(
            model_name='playergamehistory',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
