# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0008_auto_20171129_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestManyToMany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('solved', models.ManyToManyField(to='puzzle.Puzzle')),
            ],
        ),
    ]
