# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0010_auto_20171129_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergamehistory',
            name='solved',
            field=models.ManyToManyField(blank=True, related_name='solved', to='puzzle.Puzzle'),
        ),
        migrations.AlterField(
            model_name='playergamehistory',
            name='toSolve',
            field=models.ManyToManyField(blank=True, related_name='toSolve', to='puzzle.Puzzle'),
        ),
    ]
